name: learn-github-actions
on:
  push:
    branches: [ main ]  
  push:
    branches: [ main ]
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: ls -la 